services:
  - type: web
    name: instagram-auto-reply-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 1 -b 0.0.0.0:$PORT app:app
    envVars:
      - key: IG_ACCESS_TOKEN
        sync: false
      - key: IG_USER_ID
        sync: false
      - key: IG_MAX_COMMENTS
        value: "50"
      - key: API_KEY
        sync: false
